version: '3'

services:
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
    expose:
      - '3306'
  web:
    build: './web/.'
    ports:
      - '8081:80'
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./web/index.php:/var/www/html/index.php
